const assert = require('assert'); // part of node library
const ganache = require('ganache-cli');
const Web3 = require('web3');
const web3 = new Web3(ganache.provider());
const { interface, bytecode } = require('../compile');

let accounts;
let inbox;

beforeEach(async () => {
  // Get a list of all accounts generated by ganache
  accounts = await web3.eth.getAccounts();

  // Use one of the accounts to deploy the contract
  inbox = await new web3.eth.Contract(JSON.parse(interface))
    .deploy({
      data: bytecode,
      arguments: ['Hi There!!!'],
    })
    .send({
      from: accounts[0],
      gas: '1000000',
    });
});

describe('Inbox', () => {
  it('deploys a contract', () => {
    assert.ok(inbox.options.address);
  });

  it('has a default message', async () => {
    const message = await inbox.methods.message().call();
    assert.strictEqual(message, 'Hi There!!!');
  });

  it('can update the message', async () => {
    await inbox.methods.setMessage('LOL').send({from: accounts[1]});
    const message = await inbox.methods.message().call();

    assert.strictEqual(message, 'LOL');
  });
})

